version: '3'

services: 
  php-fpm:
    container_name: "php"
    build: 
      context: "./php/"
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    container_name: "blog_mysql"
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports: 
      - "3306:3306"
    expose:
      - "3306"
    volumes:
    - "../log:/var/log/mysql/"
    - "./data:/var/lib/mysql"
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8585:80"
    container_name: blog_admin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks: 
      - backend
  apache:
    container_name: "blog_apache"
    build: "./apache/"
    depends_on:
      - php-fpm
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
networks:
  frontend:
  backend: